FROM node:18-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./

RUN npm install && npm rebuild bcrypt --build-from-source

RUN apk del python3 make g++

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
